//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class BlockUtils
{
	public static float GetHeight(GameObject obj) {
		return (GetUpperBoundValue (obj) - GetLowerBoundValue (obj));
	}

	public static float GetLowerBoundValue(GameObject obj) {
		Transform tr = obj.transform.Find ("LowerBound");
		if (!tr)
			return (0);
		float pos = tr.localPosition.y;
		float globScale = obj.transform.localScale.y;
		
		return (pos * globScale);
	}

	public static float GetUpperBoundValue(GameObject obj) {
		Transform tr = obj.transform.Find ("UpperBound");
		if (!tr)
			return (0);
		float pos = tr.localPosition.y;
		float globScale = obj.transform.localScale.y;
		
		return (pos * globScale);
	}

	public static bool IsValid(GameObject obj)
	{
		return (obj.transform.Find ("LowerBound") && obj.transform.Find ("UpperBound"));
	}
}


